#!/usr/bin/env bash
# Generate Config.local.xcconfig (git-ignored) from Deploy/.env so BOTH the Xcode GUI build
# and `make ios-deploy` bake the REAL Tailscale host (and auto-detected Team ID) into the app,
# instead of the placeholders committed in Config.xcconfig. Config.xcconfig ends with
# `#include? "Config.local.xcconfig"`, so these values override the placeholders.
#
# Idempotent. Safe no-op when .env / TS_HOST is absent (the optional include is just skipped).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_env

LOCAL="$REPO_ROOT/Config.local.xcconfig"
host="${TS_HOST:-}"
team="$(detect_team_id 2>/dev/null || true)"

# Fall back to a real (non-placeholder) value already in Config.xcconfig if env/detect missed.
xc() { grep -E "^[[:space:]]*$1[[:space:]]*=" "$REPO_ROOT/Config.xcconfig" 2>/dev/null | head -n1 | sed -E "s/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//"; }
[[ -z "$host" ]] && { v="$(xc DASHBOARD_HOST)"; [[ "$v" != "macmini.example.ts.net" ]] && host="$v"; }

# Monotonic build number from the git commit count, so every build with new commits is
# strictly newer than the installed one — that's what makes the in-app "Update available"
# banner reliably fire (it compares the published build to CFBundleVersion). Baked into BOTH
# GUI and CLI builds via this include, and matched by version.json in build_and_install_ota.sh.
build="$(git -C "$REPO_ROOT" rev-list --count HEAD 2>/dev/null || true)"

{
  echo "// AUTO-GENERATED from Deploy/.env by Deploy/gen_ios_config.sh — DO NOT edit or commit."
  echo "// git-ignored; regenerated by \`make ios-generate\` / \`make ios-deploy\`."
  [[ -n "$host" ]] && echo "DASHBOARD_HOST = $host"
  [[ "$team" =~ ^[A-Z0-9]{10}$ ]] && echo "DEVELOPMENT_TEAM = $team"
  # Both the build number AND the visible version derive from the commit count, so each deploy
  # shows a new, strictly-increasing version (0.1.<count>) instead of a static 0.1.0.
  [[ "$build" =~ ^[0-9]+$ ]] && echo "CURRENT_PROJECT_VERSION = $build"
  [[ "$build" =~ ^[0-9]+$ ]] && echo "MARKETING_VERSION = 0.1.$build"
  # NEXT channel: a sibling app installable ALONGSIDE stable — distinct bundle id (automatic
  # signing self-provisions it; the widget id follows as <id>.next.widget), the next server's
  # HTTPS port, and a distinguishable home-screen name.
  if [[ "$DASHBOARD_CHANNEL" != "stable" ]]; then
    base_bundle="$(xc PRODUCT_BUNDLE_IDENTIFIER)"
    [[ -n "$base_bundle" ]] && echo "PRODUCT_BUNDLE_IDENTIFIER = $base_bundle.$DASHBOARD_CHANNEL"
    echo "DASHBOARD_PORT = $CH_TLS_PORT"
    echo "DASHBOARD_APP_NAME = Dashboard Next"
  fi
} > "$LOCAL"

if [[ -n "$host" ]]; then
  ok "wrote ${LOCAL#$REPO_ROOT/}: DASHBOARD_HOST=$host${team:+  DEVELOPMENT_TEAM=$team}"
else
  warn "no TS_HOST in Deploy/.env and Config.xcconfig host is the placeholder — set TS_HOST so the app can reach the server."
fi
