#!/usr/bin/env bash
# Deploy/refresh_schemas.sh — regenerate docs/SCHEMAS.md from the live BigQuery tables +
# Drive exports and push it, so the committed schema reference tracks reality and Claude
# can read the real field shapes. Built to run UNATTENDED on a daily schedule (schedrunner):
#
#   • non-interactive and idempotent
#   • runs in an isolated git worktree, so it never disturbs the live deploy checkout
#     (its branch / working tree stay clean for `make update`'s git pull)
#   • a true no-op when nothing but the generated-on timestamp changed (no daily churn)
#   • field names + types only by default (safe to commit); SCHEMAS_SAMPLES=1 adds sample
#     rows (PRIVATE repo only — they contain real balances/messages)
#
# Usage:
#   bash Deploy/refresh_schemas.sh                  # push to branch schemas/auto
#   SCHEMAS_BRANCH=schemas/nightly bash Deploy/...   # push to a different branch
#   SCHEMAS_SAMPLES=1 bash Deploy/refresh_schemas.sh # also dump a few rows (private repo)
#
# Needs the Mac's gcloud Application Default Credentials + the Drive mount — both present
# on the dashboard host, which is why this runs there (not in a sandbox).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_env

BRANCH="${SCHEMAS_BRANCH:-schemas/auto}"

c_bold "== refresh data schemas → docs/SCHEMAS.md =="

# 1. Make sure the sidecar venv can reach BigQuery, else the BQ section comes out empty.
PY="$REPO_ROOT/bq_sidecar/.venv/bin/python"
[[ -x "$PY" ]] || PY="python3"
if ! "$PY" -c 'import google.cloud.bigquery' 2>/dev/null; then
  info "sidecar venv missing google-cloud-bigquery — building it (make bq)"
  make -C "$REPO_ROOT" bq
  PY="$REPO_ROOT/bq_sidecar/.venv/bin/python"
fi

# 2. Work in a throwaway worktree checked out at the current origin/main, so we never
#    touch the live deploy checkout's branch or working tree.
git -C "$REPO_ROOT" fetch --quiet origin main
WTBASE="$(mktemp -d)"; WT="$WTBASE/schemas-wt"
cleanup() { git -C "$REPO_ROOT" worktree remove --force "$WT" 2>/dev/null || true; rm -rf "$WTBASE"; }
trap cleanup EXIT
git -C "$REPO_ROOT" worktree add --quiet --detach "$WT" origin/main

# 3. Generate into the worktree using the live venv (cwd = the worktree's bq_sidecar so
#    `import app` resolves there; the venv just supplies the BigQuery client lib).
( cd "$WT/bq_sidecar" && SCHEMAS_SAMPLES="${SCHEMAS_SAMPLES:-0}" "$PY" dump_schemas.py "$WT/docs/SCHEMAS.md" ) \
  || fail "schema dump failed — check gcloud ADC / Drive mount"

# 4. Skip cleanly if the only thing that changed is the generated-on timestamp line.
git -C "$WT" add docs/SCHEMAS.md
substantive="$(git -C "$WT" diff --cached -U0 -- docs/SCHEMAS.md \
  | grep -E '^[+-]' | grep -vE '^(\+\+\+|---)' | grep -vF '_Generated by `make schemas`' || true)"
if [[ -z "$substantive" ]]; then
  ok "no schema changes since last run — nothing to push"
  exit 0
fi

# 5. Commit + push the rolling branch (replace it so it stays = main + this one commit).
git -C "$WT" -c user.name="dashboard schemas" -c user.email="${GIT_AUTHOR_EMAIL:-schemas@dashboard.local}" \
  commit --quiet -m "Schemas: refresh docs/SCHEMAS.md from live BigQuery + Drive exports"
for i in 1 2 3 4; do
  if git -C "$WT" push --force-with-lease origin "HEAD:refs/heads/$BRANCH"; then
    ok "pushed docs/SCHEMAS.md → branch '$BRANCH'"
    info "Open a PR from '$BRANCH' (or tell Claude the branch) to update the schema reference."
    exit 0
  fi
  warn "push failed — retry $i"; sleep $((2 ** i))
done
fail "could not push '$BRANCH' after retries"
